name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Pull latest changes
      run: git pull origin main

    - name: Install dependencies
      run: npm i

    - name: Install PM2 globally
      run: npm install -g pm2

    - name: Add npm global bin to PATH (temporary)
      run: echo "$(npm bin -g)" >> $GITHUB_PATH

    - name: Verify PM2 installation
      run: pm2 --version

    - name: Restart application with PM2
      run: pm2 restart all
